### ISSUE TITLE
Consider transfer to ros-perception org

### ISSUE THREAD

**Issue by Kukanani** [Kukanani/vision_msgs_examples#5]
@SteveMacenski, thoughts on moving this examples repository to the ros-perception org? I don't know what the convention is for repos like this one.

**Comment by SteveMacenski** [comment]
3 options that I see:
- We leave it here and just link against it
- We transfer it to ros-perception as a new repo
- We migrate this into the `vision_msgs` repo. So create a directory for `vision_msgs` so that `vision_msgs_examples` can sit next to it. Just need to update the readme for the parent level directory. 

My preference of the 3 is option 1 or 3. The major issue with that is when when we release `vision_msgs`, those example packages also gets released. I don't know if you've released these before, but given the openCV/PCL dependencies, that might be a pain if its not been done before and something's wrong. 

Many of the examples have analogs in pcl_ros or vision_opencv. I think we could live without these in `ros-perception` unless we intend to really support these examples long term as demos people will use. Given the zero stars / watchers, I'm not sure that folks have really been relying on this project, which leads me to maybe just good to link to this in the README, requiring the least amount of effort for us now and into the future as maintainers.

**Comment by Kukanani** [comment]
I support the first option. This repo doesn't see any activity. If it begins to get more contributions/discussion, we can revisit this decision.

Thanks for the insight!
